spring.main.web-application-type=none
spring.application.name=reproaudio

# Base de datos SQLite
spring.datasource.url=jdbc:sqlite:reproaudio.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.community.dialect.SQLiteDialect

spring.sql.init.mode=never

# Configuración para SQLite con autoincrement
#spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
#spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false

# Para que Hibernate cree la secuencia correctamente
#spring.jpa.properties.hibernate.id.new_generator_mappings=true
#spring.jpa.properties.hibernate.id.optimizer.pooled.preferred=pooled-lo


# Logging
logging.level.root=INFO
#logging.level.com.minacon=DEBUG